apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include all manifests in this directory
resources:
  - namespace.yaml
  - frontend.yaml
  - api.yaml
  - ml-service.yaml
  - ingressroutes.yaml
  - servicemonitor.yaml

# Namespace
namespace: sentinel-mesh
